### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by evilpacket** [coder13/Meta#2]
Got this error while running against another project.

```
/Users/adam_baldwin/Documents/projects/Meta/check.js:556
	ce.raw = ce.name + '(' + (ce.arguments ? ce.arguments.join(','):'') + ')';
	                                                      ^
TypeError: Cannot convert object to primitive value
    at Array.join (native)
    at Scope.resolveCallExpression (/Users/adam_baldwin/Documents/projects/Meta/check.js:556:56)
    at Scope.resolveStatement (/Users/adam_baldwin/Documents/projects/Meta/check.js:259:19)
    at /Users/adam_baldwin/Documents/projects/Meta/check.js:641:10
    at Array.forEach (native)
    at Scope.traverse (/Users/adam_baldwin/Documents/projects/Meta/check.js:638:23)
    at Scope.resolveFunctionExpression (/Users/adam_baldwin/Documents/projects/Meta/check.js:609:11)
    at Scope.resolveExpression (/Users/adam_baldwin/Documents/projects/Meta/check.js:472:19)
    at Scope.resolveMemberExpression (/Users/adam_baldwin/Documents/projects/Meta/check.js:579:17)
    at Scope.resolveName (/Users/adam_baldwin/Documents/projects/Meta/check.js:572:15)
```

**Comment by coder13** [comment]
I added a flag (-d) that will tell you where where in the code you're analyzing it errored. It'd help me if I knew what the code was that it errored on.

**Comment by evilpacket** [comment]
K I'll pull and try again. Can't remember what I tested but I'll try a bunch.
